### ISSUE TITLE
Alter geo image in EUM to show specific regions

### ISSUE THREAD

**Issue by elyse-appd** [Appdynamics/demomonkey#55]
Any idea how we can potentially alter the images below so that we show specific regions instead of global i.e. show only ANZ region or EMEA region or even just the UK

![image](https://user-images.githubusercontent.com/53415734/67350610-a77f6b80-f5a7-11e9-9b52-8bb2f6ba17a8.png)

![image](https://user-images.githubusercontent.com/53415734/67350667-d8f83700-f5a7-11e9-9a85-388581ffe33b.png)

**Comment by svrnm** [comment]
Thanks for opening this as issue, makes it easier for me to track.

A few words on that:

- One thing I definitely can look into is changing the "impact color" of specific countries, so you can make sure that your story is played around the right place in the world.

- Showing only the specific region instead globally is a little bit more nuanced: The upper widget does not allow that and I try not to add features into DM, that are not possible with the real product, since this will open requirements from the customer we can't provide later. For the "Geo Dashboard" there is a feature in the product you can use. Click on the Arrow besides the "House" and set Home to your preferred country.

![Screenshot 2019-10-23 at 09 21 15](https://user-images.githubusercontent.com/1519757/67367977-cc0f1f80-f576-11e9-82d3-404f59c85c0c.png)

**Comment by elyse-appd** [comment]
Awesome, thanks for the info :) I'll try the point 2 but sorry, should have
been more precise.  I mean the impact/activity colour :) - even if it stays
global, if I can zoom in on New Zealand for example, I'm hoping we can
mimic some data in there via impact colours.



*Elyse Zafra Yu* | Senior Sales Engineer, NZ

Mobile +64 21 368 738

The Application Intelligence Company

See why AppDynamics is the world's #1 APM solution
<https://www.appdynamics.com/customers/> | Watch our video
<https://urldefense.proofpoint.com/v2/url?u=https-3A__fpdl.vimeocdn.com_vimeo-2Dprod-2Dskyfire-2Dstd-2Dus_01_2480_5_137403850_408145042.mp4-3Ftoken-3D1553265052-2D0x180bb2ee7162520d0d399e2bdc9a7b877d660ac2&d=DwMF-g&c=3_5eq9zYXWRS8ywqccmjfTRKM8mRLoQp6HBg1Tdb_Pc&r=xBGcYpK1jaQEpnx7tT1sA9cQ1UXG9BT1iqkm8J-Y9Xw&m=s-4rt2oinhOaK1k1bthJ0cUpXFcBBzC6qTBgzUwNYKA&s=C1WTDeBrrMFbGlbvDYa6kh-kSt4ugkunEcMsQslbDWU&e=>
 |
 Try our FREE Trial
<https://portal.appdynamics.com/account/signup/signupForm>  |  Twitter
<https://urldefense.proofpoint.com/v2/url?u=https-3A__twitter.com_appdynamics&d=DwMF-g&c=3_5eq9zYXWRS8ywqccmjfTRKM8mRLoQp6HBg1Tdb_Pc&r=xBGcYpK1jaQEpnx7tT1sA9cQ1UXG9BT1iqkm8J-Y9Xw&m=s-4rt2oinhOaK1k1bthJ0cUpXFcBBzC6qTBgzUwNYKA&s=0RnfSrh9WflaD6Ol11p8SNOGsOuaR-cBgAtQ_KP9HJ8&e=>
 |
 LinkedIn
<https://urldefense.proofpoint.com/v2/url?u=https-3A__www.linkedin.com_company_appdynamics&d=DwMF-g&c=3_5eq9zYXWRS8ywqccmjfTRKM8mRLoQp6HBg1Tdb_Pc&r=xBGcYpK1jaQEpnx7tT1sA9cQ1UXG9BT1iqkm8J-Y9Xw&m=s-4rt2oinhOaK1k1bthJ0cUpXFcBBzC6qTBgzUwNYKA&s=9RXm6cdElP7s699IeFdZT-svMdDc-sMJvMtDFhy6F7k&e=>
 |
 appdynamics.com <https://www.appdynamics.com/>

**Comment by svrnm** [comment]
This feature is much more complicated than I thought... there are two cases making it difficult to implement:

- Some countries (like New Zealand) don't have an impact right now since no traffic in the demo apps is coming from there, so I have to find out if/how I can put an icon there and mimic the behaviour. 

- Some countries (like New Zealand 😖) have a huge painting area (see screenshot below), and right now I have to identify the right impact icon by looking for the one (...) circle included. 

![Screenshot 2019-10-24 at 10 07 25](https://user-images.githubusercontent.com/1519757/67466247-034d0180-f647-11e9-8689-89601d139b52.png)

I have an early version of this feature prepared, but this will not work for New Zealand and a few other countries (USA, etc.)

**Comment by svrnm** [comment]
This is fixed, although it does not work for some geos.
